import type { AppData } from '../types';

export const seedData: AppData = {
  projects: [
    {
      id: 'p1',
      name: 'Puzzle Quest Mobile',
      platform: 'iOS',
      genre: 'Puzzle',
      status: 'active',
      color: '#ff6b35',
      createdAt: '2025-01-01',
    },
    {
      id: 'p2',
      name: 'Idle Farm Android',
      platform: 'Android',
      genre: 'Idle/Casual',
      status: 'active',
      color: '#3b82f6',
      createdAt: '2025-01-15',
    },
    {
      id: 'p3',
      name: 'Racing Legends',
      platform: 'Cross-platform',
      genre: 'Racing',
      status: 'active',
      color: '#00c48c',
      createdAt: '2025-02-01',
    },
  ],
  members: [
    {
      id: 'm1',
      name: 'Nguyen Van A',
      email: 'a@example.com',
      role: 'TESTER',
      avatarColor: '#ff6b35',
      initials: 'NV',
      joinedAt: '2025-01-01',
    },
    {
      id: 'm2',
      name: 'Tran Thi B',
      email: 'b@example.com',
      role: 'MANAGER',
      avatarColor: '#3b82f6',
      initials: 'TB',
      joinedAt: '2025-01-01',
    },
    {
      id: 'm3',
      name: 'Le Van C',
      email: 'c@example.com',
      role: 'TESTER',
      avatarColor: '#00c48c',
      initials: 'LC',
      joinedAt: '2025-01-10',
    },
  ],
  tasks: [
    {
      id: 't1',
      title: 'Test login flow',
      description: 'Verify login with email/password',
      projectId: 'p1',
      assigneeId: 'm1',
      status: 'done',
      priority: 'P0',
      weight: 3,
      deadline: '2025-06-10',
      createdAt: '2025-06-01',
      eisenhower: { urgent: true, important: true, autoClassified: true },
      tags: ['auth', 'critical'],
      completedAt: '2025-06-09',
    },
    {
      id: 't2',
      title: 'Test in-app purchases',
      description: 'Verify IAP flow and receipts',
      projectId: 'p1',
      assigneeId: 'm1',
      status: 'in-testing',
      priority: 'P1',
      weight: 4,
      deadline: '2025-06-20',
      createdAt: '2025-06-05',
      eisenhower: { urgent: false, important: true, autoClassified: true },
      tags: ['payment'],
    },
    {
      id: 't3',
      title: 'Performance benchmark',
      description: 'Run benchmarks on low-end devices',
      projectId: 'p2',
      assigneeId: 'm3',
      status: 'evaluating',
      priority: 'P1',
      weight: 5,
      deadline: '2025-06-25',
      createdAt: '2025-06-08',
      eisenhower: { urgent: false, important: true, autoClassified: true },
      tags: ['performance'],
    },
    {
      id: 't4',
      title: 'Check push notifications',
      description: 'Verify push on both platforms',
      projectId: 'p2',
      assigneeId: 'm3',
      status: 'backlog',
      priority: 'P2',
      weight: 2,
      deadline: '2025-07-01',
      createdAt: '2025-06-10',
      eisenhower: { urgent: false, important: false, autoClassified: true },
      tags: ['notifications'],
    },
    {
      id: 't5',
      title: 'Multiplayer stress test',
      description: 'Simulate 1000 concurrent players',
      projectId: 'p3',
      assigneeId: 'm1',
      status: 'reporting',
      priority: 'P0',
      weight: 5,
      deadline: '2025-06-15',
      createdAt: '2025-06-01',
      eisenhower: { urgent: true, important: true, autoClassified: true },
      tags: ['multiplayer', 'stress'],
    },
  ],
  statuses: [
    { id: 'backlog', label: 'Backlog', color: '#5c6280', order: 0 },
    { id: 'in-testing', label: 'In Testing', color: '#3b82f6', order: 1 },
    { id: 'evaluating', label: 'Evaluating', color: '#ffb830', order: 2 },
    { id: 'reporting', label: 'Reporting', color: '#a855f7', order: 3 },
    { id: 'done', label: 'Done', color: '#00c48c', order: 4 },
  ],
  priorities: [
    { id: 'P0', label: 'Critical', color: '#ff4757', defaultWeight: 5 },
    { id: 'P1', label: 'High', color: '#ff6b35', defaultWeight: 3 },
    { id: 'P2', label: 'Low', color: '#5c6280', defaultWeight: 1 },
  ],
  scorecards: [],
  insights: [],
  lastUpdated: new Date().toISOString(),
};
